// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type TrackArtistPairing struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	TrackUri  string
	ArtistUri sql.NullString
}

type User struct {
	ID         string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	SpotifyID  string
	StorageKey string
}
