name: Run Turso migrations

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
      TURSO_DB_NAME: ${{ secrets.TURSO_DATABASE_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Turso CLI
        run: |
          curl -sSfL https://get.tur.so/install.sh | bash
          echo "$HOME/.turso/bin" >> $GITHUB_PATH

      - name: Verify Turso installation
        run: turso --version

      - name: Authenticate with Turso
        run: turso auth login --token "$TURSO_AUTH_TOKEN"

      - name: Apply migrations
        run: |
          turso db shell "$TURSO_DB_NAME" < sql/schema-bootstrap.sql